package lambdas.helpers;

public interface ErrorCode {
    String INVALID_USER_FORMAT = "INVALID_USER_FORMAT";
    String ERROR_PROCESSING_POST_REQUEST = "ERROR_PROCESSING_POST_REQUEST";
    String USER_NOT_FOUND_OR_INCORRECT_PASSWORD = "USER_NOT_FOUND_OR_INCORRECT_PASSWORD";
    String ERROR_PROCESSING_DELETE_REQUEST = "ERROR_PROCESSING_DELETE_REQUEST";
    String INVALID_EVENT_SOURCE = "INVALID_EVENT_SOURCE";
}
