package helpers;

public interface ErrorCode {
    String INVALID_USER_FORMAT = "INVALID_USER_FORMAT";
    String ERROR_PROCESSING_POST_REQUEST = "ERROR_PROCESSING_POST_REQUEST";
    String USER_NOT_FOUND_OR_INCORRECT_PASSWORD = "USER_NOT_FOUND_OR_INCORRECT_PASSWORD";
    String METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED";
    String ERROR_PROCESSING_DELETE_REQUEST = "ERROR_PROCESSING_DELETE_REQUEST";
}
