AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infastructure for distributed image processing task scheduler'

Parameters:
  handler:
      Default: lambdas.UserService::handleRequest
      Type: String

Resources:
  UserServiceLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: UserService-lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess             
      Path: /

  UserServiceLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: UserService
      Description: Lambda for handling user creation
      Handler: !Sub '${handler}'
      Role: !GetAtt UserServiceLambdaRole.Arn 
      Runtime: java17  
      Code: lambdas/UserService.java