AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template for S3 bucket to store lambdas'

Resources:
  LambdaS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Join
        - ''
        - - !Ref 'AWS::Region'
          - '-image-processor-lambda-bucket'