name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: 'ap-northeast-1'
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: |
          cd ./aws/image-processor-lambdas
          mvn clean package
      - name: Package CloudFormation template
        run: |
          cd ./aws/cloudformation/
          aws cloudformation package --template-file image-processor-template.yaml --s3-bucket ap-northeast-1-image-processor-lambda-bucket --s3-prefix lambdas --output-template-file infrastructure-packaged.template
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy --template-file cloudformation/infrastructure-packaged.template --stack-name ImageProcessorStack --region ap-northeast-1 --capabilities CAPABILITY_NAMED_IAM --parameter-overrides MetaDataDBUsername=db_user
      - name: Run integration tests
        run: |
          cd ./aws/image-processor-lambdas/
          mvn failsafe:integration-test